// Type declarations for @cyntr/sdk.
// Generated by hand — keep in sync with src/index.js.

export interface Tenant {
  name: string;
  isolation: string;
  policy: string;
}

export interface AgentConfig {
  name: string;
  tenant: string;
  model: string;
  system_prompt: string;
  tools: string[];
  skills?: string[];
  max_turns: number;
  max_history?: number;
  rate_limit?: number;
}

export interface ChatResponse {
  agent: string;
  content: string;
  tools_used: string[] | null;
}

export interface ChatOptions {
  user?: string;
  channel?: string;
}

export interface CreateAgentOptions {
  tools?: string[];
  skills?: string[];
}

export interface Session {
  id: string;
  tenant: string;
  agent: string;
  messages: any[];
  created_at: string;
  updated_at: string;
}

export interface Memory {
  ID: string;
  Agent: string;
  Tenant: string;
  Key: string;
  Content: string;
  CreatedAt: string;
  UpdatedAt: string;
}

export interface Workflow {
  ID: string;
  Name: string;
  Description: string;
  Tenant: string;
  Steps: Step[];
}

export interface Step {
  ID: string;
  Name: string;
  Type: string;
  Config: Record<string, string>;
}

export interface WorkflowRun {
  ID: string;
  WorkflowID: string;
  Status: string;
  CurrentStep: string;
  StartedAt: string;
  CompletedAt: string;
  Error: string;
}

export interface Job {
  ID: string;
  Name: string;
  Tenant: string;
  Agent: string;
  Message: string;
  Interval: number;
  CronExpr: string;
  Enabled: boolean;
}

export interface KnowledgeDoc {
  id: string;
  title: string;
  tags: string;
  source_url?: string;
}

export interface PolicyRule {
  name: string;
  tenant: string;
  action: string;
  tool: string;
  agent: string;
  decision_str: string;
  priority: number;
}

export interface Approval {
  id: string;
  tenant: string;
  agent: string;
  user: string;
  tool: string;
  status: string;
}

export interface EvalCase {
  name?: string;
  agent?: string;
  tenant?: string;
  prompt: string;
  expected?: string;
  match?: 'contains' | 'equals' | 'regex';
}

export interface EvalRun {
  id: string;
  agent: string;
  tenant: string;
  status: string;
  total: number;
  passed: number;
  failed: number;
  started_at?: string;
  completed_at?: string;
  results?: any[];
}

export interface AuditFilters {
  tenant?: string;
  user?: string;
  action?: string;
  since?: string;
  limit?: number;
}

export interface ClientOptions {
  timeout?: number;
  maxRetries?: number;
  retryBackoff?: number;
}

export interface StreamEvent {
  type?: string;
  content?: string;
  raw?: string;
  [k: string]: any;
}

export class CyntrError extends Error {
  status: number;
  code: string;
  requestId: string;
  constructor(status: number, code: string, message: string, requestId?: string);
}

export declare class CyntrClient {
  constructor(baseUrl?: string, apiKey?: string | null, opts?: ClientOptions);

  baseUrl: string;
  apiKey: string | null;
  timeout: number;
  maxRetries: number;
  retryBackoff: number;

  // System
  health(): Promise<Record<string, any>>;
  version(): Promise<{ version: string }>;

  // Tenants
  listTenants(): Promise<Tenant[]>;
  getTenant(tid: string): Promise<Tenant>;
  createTenant(name: string, isolation?: string, policy?: string): Promise<{ status: string; name: string }>;
  deleteTenant(tid: string): Promise<{ status: string }>;

  // Agents
  listAgents(tenant: string): Promise<string[]>;
  createAgent(tenant: string, config: Partial<AgentConfig>): Promise<{ status: string; agent: string }>;
  createAgent(
    tenant: string,
    name: string,
    model?: string,
    prompt?: string,
    opts?: CreateAgentOptions
  ): Promise<{ status: string; agent: string }>;
  getAgent(tenant: string, name: string): Promise<AgentConfig>;
  updateAgent(tenant: string, name: string, fields: Partial<AgentConfig>): Promise<{ status: string }>;
  deleteAgent(tenant: string, name: string): Promise<{ status: string }>;
  chat(tenant: string, agent: string, message: string, opts?: ChatOptions): Promise<ChatResponse>;
  chatStream(tenant: string, agent: string, message: string): AsyncGenerator<StreamEvent, void, void>;

  // Sessions
  listSessions(tenant: string, agent: string): Promise<string[]>;
  getSession(tenant: string, agent: string, sid: string): Promise<any[]>;
  /** @deprecated Use getSession. */
  getSessionMessages(tenant: string, agent: string, sid: string): Promise<any[]>;
  clearSession(tenant: string, agent: string, sid?: string): Promise<{ status: string }>;

  // Memories
  listMemories(tenant: string, agent: string): Promise<Memory[]>;
  deleteMemory(tenant: string, agent: string, mid: string): Promise<{ status: string }>;

  // Skills
  listSkills(): Promise<any[]>;
  installSkill(name: string): Promise<{ status: string }>;
  uninstallSkill(name: string): Promise<{ status: string }>;
  searchSkills(query: string): Promise<any[]>;

  // Workflows
  listWorkflows(tenant?: string): Promise<string[]>;
  getWorkflow(id: string): Promise<Workflow>;
  registerWorkflow(def: any): Promise<{ workflow_id: string }>;
  runWorkflow(tenant: string, name: string, inputs?: Record<string, any>): Promise<{ run_id: string }>;
  listWorkflowRuns(): Promise<WorkflowRun[]>;
  getWorkflowRun(id: string): Promise<WorkflowRun>;

  // Knowledge
  listKnowledge(): Promise<KnowledgeDoc[]>;
  ingestKnowledge(title: string, content: string, tags?: string | string[] | null): Promise<{ status: string; id: string }>;
  searchKnowledge(query: string, limit?: number): Promise<any[]>;
  deleteKnowledge(id: string): Promise<{ status: string }>;

  // Audit
  queryAudit(filters?: AuditFilters): Promise<any[]>;

  // Eval
  runEval(agent: string, tenant: string, cases: EvalCase[]): Promise<string>;
  getEvalRun(id: string): Promise<EvalRun>;
  listEvalRuns(): Promise<EvalRun[]>;

  // Policies
  listPolicyRules(): Promise<PolicyRule[]>;
  testPolicy(body: Record<string, string>): Promise<any>;

  // Schedules / Federation / Approvals / Channels
  listSchedules(): Promise<Job[]>;
  addSchedule(body: Record<string, any>): Promise<{ status: string; id: string }>;
  removeSchedule(id: string): Promise<{ status: string }>;
  listPeers(): Promise<any[]>;
  joinPeer(name: string, endpoint: string, secret?: string): Promise<{ status: string }>;
  removePeer(name: string): Promise<{ status: string }>;
  listApprovals(): Promise<Approval[]>;
  approve(id: string, decidedBy?: string): Promise<{ status: string }>;
  deny(id: string, decidedBy?: string): Promise<{ status: string }>;
  listChannels(): Promise<any[]>;
}
